// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:challenges/sqflite/models/personne.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(PersonneAdapter());
  }
}
